# POST https://techconnect-nigeria-2027.onrender.com/api/payment/initialize
# Content-Type: application/json

# {
#     "email": "fidelismartha23@gmail.com",
#     "ticket": "Premium"
# }



# POST https://techconnect-nigeria-2027.onrender.com/api/payment/verify/T500013077508929
# Content-Type: application/json

# {
#     "name": "queen egiriga fidelis",
#     "email": "fidelismartha23@gmail.com",
#     "phone": "09138372313",
#     "ticket": "Premium"
# }

# GET https://techconnect-nigeria-2027.onrender.com/api/registrations


# POST https://techconnect-nigeria-2027.onrender.com/api/payment/initialize
# Content-Type: application/json

# {
#     "name": "queen egiriga fidelis",
#     "email": "fidelismartha23@gmail.com",
#     "phone": "09138372313",
#     "ticket": "Premium"
# }

POST https://techconnect-nigeria-2027.onrender.com/api/payment/verify/T689843012007450
Content-Type: application/json

{
    "name": "queen egiriga fidelis",
    "email": "fidelismartha23@gmail.com",
    "phone": "09138372313",
    "ticket": "Premium"
}