

# GET https://techconnect-nigeria-2027.onrender.com/api/registrations


# POST https://techconnect-nigeria-2027.onrender.com/api/payment/initialize
# Content-Type: application/json

# {
#    "name": "martha fidelis",
#     "email": "marthafidelis892@gmail.com",
#     "phone": "09138372313",
#     "ticket": "Regular"
# }

# POST https://techconnect-nigeria-2027.onrender.com/api/payment/verify/T733677411374092
# Content-Type: application/json

# {
#     "name": "martha fidelis",
#     "email": "marthafidelis892@gmail.com",
#     "phone": "09138372313",
#     "ticket": "Regular"
# }

PATCH http://localhost:5000/api/tickets/TC-F388F07D/use